spring:
  session:
    store-type: redis
zuul: 
  retryable: true
  routes:
    order-management-ms: 
      path: /order-management/**
  sensitiveHeaders: Set-Cookie,Authorization
security:
  user:
    name: gateway
    password: password

